version: "3.9"

networks:
  default:
    external:
      name: digitalocean-apps_default

services:
  blog:
    container_name: blog
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    environment:
      # Make it easy to use `rails credentials:edit`
      EDITOR: nano
      WEBPACKER_DEV_SERVER_HOST: '0.0.0.0'
    volumes:
      - .:/code
    ports:
      # For webpack-dev-server
      - "3035:3035"
    labels:
      - "traefik.http.routers.blog.rule=Host(`blog.localhost`)"
      # Tell Traefik to use the port 3000 to connect to `web`
      - traefik.http.services.blog.loadbalancer.server.port=3000